### ISSUE TITLE
Fix tig-explorer issues

### ISSUE THREAD

**Issue by zhimsel** [zhimsel/dotfiles#19]
https://github.com/iberianpig/tig-explorer.vim

For some reason, tig-explorer has a hard time returning to the correct buffer when it takes over a window.
When tig is closed, it often returns to the incorrect buffer.

It also is unable to deal with manually-set `$GIT_DIR` and `$GIT_WORK_TREE` env vars (when `.git` is not present).

I'll probably end up needing to rewrite a lot of the plugin.

# To-do
- [ ] Use `$TIG_SCRIPT` instead of hacking a temporary `tigrc` file; alternatively, call a custom config file that sources the users'.
- [ ] Use `-C` option instead of having to temporarily `lcd` to the project root
- [ ] Figure out how to restore the proper buffer

**Comment by zhimsel** [comment]
Not going to bother, since I just use `Tig` directly in a Terminal window now. It's slightly clunky (due to the nested vim sessions if I edit a commit message), but it works well enough.
