### ISSUE TITLE
Rework zsh prompt

### ISSUE THREAD

**Issue by zhimsel** [zhimsel/dotfiles#24]
# Goals
- Faster (most important)
- Cleaner looking
- No large dependencies (e.g. haskell for the git prompt)

# Required information
- User/host (only if on a remote machine)
- Path (preferably truncated in some way)
- Git branch/status (fast or async)
- `viins`/`vicmd` mode
- Previous command's return code
- Previous command's run time (maybe)
- Indicator for backgrounded programs

# To-do
- [x] Settle on a prompt plugin (or manually created one)
- [x] Configure said prompt
- [x] Move "env metadata" parts to ZLE widget that displays the value of the configured env vars or command outputs with support for local additions (note to self: `zle -R [display-string]`). Maybe include more-detailed git status?
- [ ] ~Figure out how to get git info to update when using the `^e` ZLE widget.~

**Comment by zhimsel** [comment]
https://github.com/denysdovhan/spaceship-prompt
https://github.com/denysdovhan/spaceship-prompt/blob/master/lib/section.zsh

**Comment by zhimsel** [comment]
https://github.com/sindresorhus/pure

**Comment by zhimsel** [comment]
https://github.com/sindresorhus/pure
https://github.com/therealklanni/purity
https://github.com/intelfx/pure
https://github.com/dfurnes/purer
