### ISSUE TITLE
Enable live-reloading of vim's config

### ISSUE THREAD

**Issue by zhimsel** [zhimsel/dotfiles#29]
# To-do
- [x] Figure out what breaks (and add to this list)
- [x] Place all autocommands in self-clearing groups
- [x] augroups not reloading
