### ISSUE TITLE
Refactor folder structure and symlinking

### ISSUE THREAD

**Issue by zhimsel** [zhimsel/dotfiles#3]
- [x] Rewrite install script in Python for better/smarter symlinking (don't rely on assumed paths)
  - [x] Use `.$file.link` files for link destinations
  - [x] Must be idempotent
  - [x] make-based installer?
- [x] Reorganize config files by program/app (while smartly symlinking) #

**Comment by zhimsel** [comment]
Make installer moved to separate task #10
